[package]
name = "maxmind-geoip-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
env_logger = "0.11.3"
log = "0.4.21"
maxminddb = { version = "0.24.0", features = ["mmap"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
